"""
=========================================================
SwitchGuardAI Data Loader
=========================================================

Loads the raw dataset generated by the simulator.

Responsibilities
----------------
1. Read CSV
2. Parse timestamps
3. Return pandas DataFrame

Author : Tanishka
Project : SwitchGuardAI
"""

import pandas as pd


RAW_DATA_PATH = "data/raw/switch_machine_dataset.csv"


class DataLoader:

    def __init__(self, file_path=RAW_DATA_PATH):
        self.file_path = file_path

    def load_data(self):
        """
        Load the raw dataset.

        Returns
        -------
        pandas.DataFrame
        """

        df = pd.read_csv(
            self.file_path,
            parse_dates=["Timestamp"]
        )

        return df


if __name__ == "__main__":

    loader = DataLoader()

    dataset = loader.load_data()

    print("=" * 60)
    print("DATASET LOADED")
    print("=" * 60)

    print(dataset.head())

    print("\nShape :", dataset.shape)